---
- name: Update all
  hosts: webservers
  remote_user: [insert username]
  become: yes

  tasks:
    - name: update then upgrade
      apt:
        update_cache: yes
        upgrade: yes
...